config/routes.rb
Rails.application.routes.draw do
  resources :dinners

  resources :dinner_cookers
  resources :todos

  root 'dinner_cookers#index'

end

app/models/dinner.rb
class Dinner < ActiveRecord::Base
	belongs_to :dinner_cooker
end

app/models/dinner_cooker.rb
class DinnerCooker < ActiveRecord::Base
	has_many :dinners
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dinner_cookers_controller.rb
class DinnerCookersController < ApplicationController
  before_action :set_dinner_cooker, only: [:show, :edit, :update, :destroy]

  # GET /dinner_cookers
  # GET /dinner_cookers.json
  def index
    # @dinner_cookers = DinnerCooker.all
    @dinner_cookers = DinnerCooker.all.joins(:dinners).order('dinners.date_cooked asc')
  end

  # GET /dinner_cookers/1
  # GET /dinner_cookers/1.json
  def show
  end

  # GET /dinner_cookers/new
  def new
    @dinner_cooker = DinnerCooker.new
  end

  # GET /dinner_cookers/1/edit
  def edit
  end

  # POST /dinner_cookers
  # POST /dinner_cookers.json
  def create
    @dinner_cooker = DinnerCooker.new(dinner_cooker_params)

    respond_to do |format|
      if @dinner_cooker.save
        format.html { redirect_to @dinner_cooker, notice: 'Dinner cooker was successfully created.' }
        format.json { render :show, status: :created, location: @dinner_cooker }
      else
        format.html { render :new }
        format.json { render json: @dinner_cooker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dinner_cookers/1
  # PATCH/PUT /dinner_cookers/1.json
  def update
    respond_to do |format|
      if @dinner_cooker.update(dinner_cooker_params)
        format.html { redirect_to @dinner_cooker, notice: 'Dinner cooker was successfully updated.' }
        format.json { render :show, status: :ok, location: @dinner_cooker }
      else
        format.html { render :edit }
        format.json { render json: @dinner_cooker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dinner_cookers/1
  # DELETE /dinner_cookers/1.json
  def destroy
    @dinner_cooker.destroy
    respond_to do |format|
      format.html { redirect_to dinner_cookers_url, notice: 'Dinner cooker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dinner_cooker
      @dinner_cooker = DinnerCooker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dinner_cooker_params
      params.require(:dinner_cooker).permit(:name)
    end
end

app/controllers/dinners_controller.rb
class DinnersController < ApplicationController
  before_action :set_dinner, only: [:show, :edit, :update, :destroy]

  # GET /dinners
  # GET /dinners.json
  def index
    @dinners = Dinner.all
  end

  # GET /dinners/1
  # GET /dinners/1.json
  def show
  end

  # GET /dinners/new
  def new
    @dinner = Dinner.new
  end

  # GET /dinners/1/edit
  def edit
  end

  # POST /dinners
  # POST /dinners.json
  def create
    date = Date.civil(*params[:dinner].sort.map(&:last).map(&:to_i))
    @dinner = Dinner.new({ date_cooked: date, dinner_cooker_id: dinner_params[:dinner_cooker] })
    respond_to do |format|
      if @dinner.save
        format.html { redirect_to @dinner, notice: 'Dinner was successfully created.' }
        format.json { render :show, status: :created, location: @dinner }
      else
        format.html { render :new }
        format.json { render json: @dinner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dinners/1
  # PATCH/PUT /dinners/1.json
  def update
    respond_to do |format|
      if @dinner.update(dinner_params)
        format.html { redirect_to @dinner, notice: 'Dinner was successfully updated.' }
        format.json { render :show, status: :ok, location: @dinner }
      else
        format.html { render :edit }
        format.json { render json: @dinner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dinners/1
  # DELETE /dinners/1.json
  def destroy
    @dinner.destroy
    respond_to do |format|
      format.html { redirect_to dinners_url, notice: 'Dinner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dinner
      @dinner = Dinner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dinner_params
      params.require(:dinner).permit(:date_cooked, :dinner_cooker)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params[:todo].permit(:name)
      # params.permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinner_cookers_helper.rb
module DinnerCookersHelper
end

app/helpers/dinners_helper.rb
module DinnersHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/dinner_cookers/_form.html.erb
<%= form_for(@dinner_cooker) do |f| %>
  <% if @dinner_cooker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dinner_cooker.errors.count, "error") %> prohibited this dinner_cooker from being saved:</h2>

      <ul>
      <% @dinner_cooker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.label :move_in_date %><br>
    <%= f.date_select :move_in_date %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dinner_cookers/edit.html.erb
<h1>Editing Dinner Cooker</h1>

<%= render 'form' %>

<%= link_to 'Show', @dinner_cooker %> |
<%= link_to 'Back', dinner_cookers_path %>

app/views/dinner_cookers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dinner Cookers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dinner_cookers.each do |dinner_cooker| %>
      <tr>
        <td><%= dinner_cooker.name %></td>
        <td><%= link_to 'Show', dinner_cooker %></td>
        <td><%= link_to 'Edit', edit_dinner_cooker_path(dinner_cooker) %></td>
        <td><%= link_to 'Destroy', dinner_cooker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% if dinner_cooker.dinners.length == 0 %>
        <tr>
          <td style="padding-left: 30px;">This bitch hasn't cooked yet!</td>
        </tr>
      <% else %>
        <% dinner_cooker.dinners.each do |dinner| %>
        <tr>
          <td style="padding-left: 30px;"><%= dinner.date_cooked %></td>
        </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dinner cooker', new_dinner_cooker_path %><br><br>
  
<%= link_to 'New Dinner', new_dinner_path %>

app/views/dinner_cookers/new.html.erb
<h1>New Dinner Cooker</h1>

<%= render 'form' %>

<%= link_to 'Back', dinner_cookers_path %>

app/views/dinner_cookers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dinner_cooker.name %>
</p>

<%= link_to 'Edit', edit_dinner_cooker_path(@dinner_cooker) %> |
<%= link_to 'Back', dinner_cookers_path %>

app/views/dinners/_form.html.erb
<%= form_for(@dinner) do |f| %>
  <% if @dinner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dinner.errors.count, "error") %> prohibited this dinner from being saved:</h2>

      <ul>
      <% @dinner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dinner_cooker %><br>
    <%= f.collection_select(:dinner_cooker, DinnerCooker.all, :id, :name) %><br>
    
    <%= f.label :date_cooked %><br>
    <%= f.date_select :date_cooked %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dinners/edit.html.erb
<h1>Editing Dinner</h1>

<%= render 'form' %>

<%= link_to 'Show', @dinner %> |
<%= link_to 'Back', dinners_path %>

app/views/dinners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dinners</h1>

<table>
  <thead>
    <tr>
      <th>Date cooked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dinners.each do |dinner| %>
      <tr>
        <td><%= dinner.date_cooked %></td>
        <td><%= link_to 'Show', dinner %></td>
        <td><%= link_to 'Edit', edit_dinner_path(dinner) %></td>
        <td><%= link_to 'Destroy', dinner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dinner', new_dinner_path %>

app/views/dinners/new.html.erb
<h1>New Dinner</h1>

<%= render 'form' %>

<%= link_to 'Back', dinners_path %>

app/views/dinners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date cooked:</strong>
  <%= @dinner.date_cooked %>
</p>

<%= link_to 'Edit', edit_dinner_path(@dinner) %> |
<%= link_to 'Back', dinners_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blah</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Home', dinner_cookers_path %>
<%= yield %>

</body>
</html>

app/views/todos/_form.html.erb
<%= form_for @todo, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.name %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>